name: SM Compilation Test

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: [ "1.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Set environment variables
        run: |
          echo SCRIPTS_PATH=$GITHUB_WORKSPACE/scripting >> $GITHUB_ENV
          echo INCLUDE_PATH=$GITHUB_WORKSPACE/scripting/include >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@v1.2.1
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugins
        run: |
          for file in $SCRIPTS_PATH
          do
            echo -e "\n--- Compiling $file ---"
            spcomp -E -w234 -O2 -v2 -i $INCLUDE_PATH $file
          done
          echo "--- COMPILED FILES ---"
          ls
        working-directory: ${{ env.SCRIPTS_PATH }}